### ISSUE TITLE
Failed to load JAR in Jpype

### ISSUE THREAD

**Issue by arita291** [tcalmant/jpype-py3#18]
Hi,
I tried to load 3rd party jar like this:

```
import jpype as jp
classpath = "E:/lib/java/pdfbox-1.8.11.jar"
jp.startJVM(jp.getDefaultJVMPath(),"-ea", "-DJava.class.path=%s" % classpath)
pd = jp.JPackage("org").apache.pdfbox.pdmodel.PDDocument
document = pd.load("TheTibetansPart1.pdf")

jp.java.lang.System.out.println("Hello World "+jp.JString(document.getNumberOfPages()))
jp.shutdownJVM()

```

I got this message:
  File "python-3.4.4.amd64\lib\site-packages\jpype\_jpackage.py", line 53, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))

1) How can I check if the JAR is well loaded ? (is it a problem of folder path ???)

Kind regards

**Comment by tcalmant** [comment]
Hi,

The problem is due to a missing class, sadly JNI doesn't give enough information to find where the problem is.
After some tests, I got a working version.

1/ The classpath option is case sensitive, so you should use ``-Djava.class.path``.
2/ PDFBox requires Apache Commons Logging, so it must be added in the classpath.
3/ jp.JString shoudln't be used for conversion: it represents a string from the Java world, but doesn't act like it. As the value is already in the Python world, it should be converted using ``str()``.

The final code should look like this:

```python
import jpype as jp
import os

# Use pathsep to join JAR files
classpath = os.pathsep.join((r"commons-logging-1.2.jar", r"pdfbox-1.8.11.jar"))
jp.startJVM(jp.getDefaultJVMPath(),"-ea", "-Djava.class.path=%s" % classpath)

# Another way could be: pd = jp.JClass("org.apache.pdfbox.pdmodel.PDDocument")
pd = jp.JPackage("org").apache.pdfbox.pdmodel.PDDocument
document = pd.load(r"TheTibetansPart1.pdf")

# Use str() to convert to strings, instead of JString
jp.java.lang.System.out.println("Hello World "+str(document.getNumberOfPages()))
```

**Comment by arita291** [comment]
Hello,

It's working now.
Thank you so much, we are working on this this package,
if anything interesting, we'll let you know.

Kind regards.
